/**
 * Images Defines
 * @author Passion UI <passionui.com>
 */

export const Images = {
  OnBoarding_1: require('../assets/images/OnBoarding_5.jpg'),
  OnBoarding_2: require('../assets/images/OnBoard_3.jpg'),
  OnBoarding_3: require('../assets/images/OnBoarding_3.png'),
  // OnBoarding_3: require('../assets/images/OnBoarding_3.png'),
  ic_google: require('../assets/images/ic_google.png'),
  ic_google1: require('../assets/images/ic_google1.png'),
  ic_apple: require('../assets/images/ic_apple.png'),
  ic_apple1: require('../assets/images/ic_apple1.png'),
  ic_whatsapp: require('../assets/images/ic_whatsapp.png'),
  ic_whatsapp1: require('../assets/images/ic_whatsapp1.png'),
  ic_or_line: require('../assets/images/ic_or_line.png'),
  ic_name: require('../assets/images/ic_name.png'),
  ic_email: require('../assets/images/ic_email.png'),
  ic_phone_call: require('../assets/images/ic_phone_call.png'),
  ic_pass: require('../assets/images/ic_pass.png'),
  ic_pass_show: require('../assets/images/ic_pass_show.png'),
  ic_hidden_pass: require('../assets/images/ic_hidden_pass.png'),
  ic_forgot: require('../assets/images/ic_forgot.png'),
  ic_back: require('../assets/images/ic_back.png'),
  ic_email_back: require('../assets/images/ic_email_back.png'),
  ic_msg: require('../assets/images/ic_msg.png'),
  ic_uncheck_radio: require('../assets/images/ic_uncheck_radio.png'),
  ic_check_radio: require('../assets/images/ic_check_radio.png'),
  ic_pass_logo: require('../assets/images/ic_pass_logo.png'),
  ic_right_round: require('../assets/images/ic_right_round.png'),
  ic_home: require('../assets/images/IC_Home.png'),
  IC_Uncheck_Home: require('../assets/images/IC_Uncheck_Home.png'),
  ic_user: require('../assets/images/ic_user.png'),

  movie_1: require('../assets/images/movie_1.png'),
  movie_2: require('../assets/images/movie_2.png'),
  movie_3: require('../assets/images/movie_3.png'),
  movie_4: require('../assets/images/movie_4.png'),
  movie_5: require('../assets/images/movie_5.png'),
  movie_6: require('../assets/images/movie_6.png'),
  movie_7: require('../assets/images/movie_7.png'),
  movie_8: require('../assets/images/movie_8.png'),
  movie_9: require('../assets/images/movie_9.png'),
  movie_10: require('../assets/images/movie_10.png'),
  movie_11: require('../assets/images/movie_11.png'),
  movie_12: require('../assets/images/movie_12.png'),
  movie_13: require('../assets/images/movie_13.jpg'),

  ic_filter: require('../assets/images/ic_filter.png'),
  ic_search: require('../assets/images/ic_search.png'),
  ic_list: require('../assets/images/ic_list.png'),
  ic_download: require('../assets/images/ic_download.png'),
  ic_download1: require('../assets/images/ic_download1.png'),
  ic_play: require('../assets/images/ic_play.png'),
  ic_delete: require('../assets/images/ic_delete.png'),
  ic_delete_new: require('../assets/images/ic_delete_new.png'),
  ic_edit_profile: require('../assets/images/ic_edit_profile.png'),
  ic_profile: require('../assets/images/ic_profile.png'),
  ic_right_arrow: require('../assets/images/ic_right_arrow.png'),
  ic_right_arrow1: require('../assets/images/ic_right_arrow1.png'),
  ic_logout1: require('../assets/images/ic_logout_new.png'),
  ic_help: require('../assets/images/ic_help.png'),
  ic_help_new: require('../assets/images/ic_help_new.png'),
  ic_policy: require('../assets/images/ic_policy.png'),
  ic_privacy_policy: require('../assets/images/ic_privacy_policy.png'),
  ic_contact: require('../assets/images/ic_contact.png'),
  ic_subscription: require('../assets/images/ic_subscription.png'),
  ic_device: require('../assets/images/ic_device.png'),
  ic_avtar: require('../assets/images/ic_avtar.png'),

  ic_edit: require('../assets/images/ic_edit.png'),
  ic_dash_tras_back: require('../assets/images/ic_dash_tras_back.png'),
  ic_plus: require('../assets/images/ic_plus.png'),
  ic_play_icon: require('../assets/images/ic_play_icon.png'),
  ic_player: require('../assets/images/ic_player.png'),
  ic_player2: require('../assets/images/ic_player2.png'),

  ic_detail_back: require('../assets/images/ic_detail_back.png'),
  ic_share_new: require('../assets/images/ic_share_new.png'),

  ic_premium1: require('../assets/images/ic_premium1.png'),
  ic_premium2: require('../assets/images/ic_premium2.png'),

  avtar1: require('../assets/images/avtar1.jpg'),
  avtar2: require('../assets/images/avtar2.png'),
  ic_avatar1: require('../assets/images/ic_avatar1.jpg'),
  av_1: require('../assets/images/av_1.jpg'),
  av_2: require('../assets/images/av_2.jpg'),
  av_3: require('../assets/images/av_3.jpg'),
  av_4: require('../assets/images/av_4.jpg'),
  av_5: require('../assets/images/av_5.jpg'),
  av_6: require('../assets/images/av_6.png'),
  av_7: require('../assets/images/av_7.jpg'),
  av_8: require('../assets/images/av_8.jpg'),
  av_9: require('../assets/images/av_9.png'),

  ic_right_arrow_new: require('../assets/images/ic_right_arrow_new.png'),
  ic_user1: require('../assets/images/ic_user1.png'),

  ic_forgot_img: require('../assets/images/ic_forgot_img.png'),
  ic_otp_img: require('../assets/images/ic_otp_img.png'),
  ic_interest1: require('../assets/images/ic_interest1.png'),
  ic_interest2: require('../assets/images/ic_interest2.png'),
  ic_watchlist: require('../assets/images/ic_watchlist.png'),

  ic_play_watch_now: require('../assets/images/ic_play_watch_now.png'),
  ic_add_bookmark: require('../assets/images/ic_add_bookmark.png'),
  ic_setting: require('../assets/images/ic_setting.png'),
  ic_transaction_history: require('../assets/images/ic_transaction_history.png'),

  ic_avoid: require('../assets/images/ic_avoid.png'),

  Cast1: require('../assets/images/Cast1.png'),
  Cast2: require('../assets/images/Cast2.png'),
  Cast3: require('../assets/images/Cast3.png'),
  Cast4: require('../assets/images/Cast4.png'),
  Cast5: require('../assets/images/Cast5.png'),
  Page: require('../assets/images/page.png'),
  
  DispatchReport: require('../assets/images/DispatchReport.png'),
  DispatchMaterial: require('../assets/images/DispatchMaterial.png'),
  PendingTesting: require('../assets/images/PendingTesting.png'),
  InwardRegister: require('../assets/images/InwardRegister.png'),
  ProcessStatus: require('../assets/images/ProcessStatus.png'),
  PLLOGO: require('../assets/images/PL-logo.png'),
  TTR: require('../assets/images/TTR.png'),
  TAP: require('../assets/images/TAP.png'),
  IAP: require('../assets/images/IAP.png'),
  activityLog: require('../assets/images/activityLog.png'),
  activityLog1: require('../assets/images/activityLog1.png'),
  closed: require('../assets/images/closed.png'),
  scheduleIcon: require('../assets/images/scheduleIcon.png'),
  MIS: require('../assets/images/MIS.png'),
  ControlCenter: require('../assets/images/ControlCenter.png'),
  Dashboard: require('../assets/images/Dashboard.png'),
  Profilee: require('../assets/images/Profilee.png'),
  DownArrow: require('../assets/images/DownArrow.png'),

  reload: require('../assets/images/reload.png'),
  close: require('../assets/images/close.png'),
  check: require('../assets/images/check.png'),
  forbidden: require('../assets/images/forbidden.png'),
  db: require('../assets/images/db.png'),
  a_db: require('../assets/images/a_db.png'),
  UserBottom: require('../assets/images/UserBottom.png'),
  a_UserBottom: require('../assets/images/a_UserBottom.png'),//
  a_cc: require('../assets/images/a_cc.png'),//
  cc: require('../assets/images/cc.png'),//a_UserBottom
  ms: require('../assets/images/ms.png'),//a_UserBottom
  a_ms: require('../assets/images/a_ms.png'),//a_UserBottom
}
