/**
 * Images Defines
 * @author Passion UI <passionui.com>
 */

export const Images = {
  a_cc: require('../assets/images/a_cc.png'),
  a_db: require('../assets/images/a_db.png'),
  a_ms: require('../assets/images/a_ms.png'),
  a_UserBottom: require('../assets/images/a_UserBottom.png'),
  activityLog: require('../assets/images/activityLog.png'),
  activityLog1: require('../assets/images/activityLog1.png'),
  bgimg: require('../assets/images/bgimg.png'),
  cc: require('../assets/images/cc.png'),
  check: require('../assets/images/check.png'),
  close: require('../assets/images/close.png'),
  close1: require('../assets/images/close1.png'),
  closed: require('../assets/images/closed.png'),
  ControlCenter: require('../assets/images/ControlCenter.png'),
  Dashboard: require('../assets/images/Dashboard.png'),
  ic_DataFound: require('../assets/images/DataFound.png'),
  db: require('../assets/images/db.png'),
  DispatchMaterial: require('../assets/images/DispatchMaterial.png'),
  DispatchReport: require('../assets/images/DispatchReport.png'),
  DownArrow: require('../assets/images/DownArrow.png'),
  forbidden: require('../assets/images/forbidden.png'),
  IAP: require('../assets/images/IAP.png'),
  ic_avtar: require('../assets/images/ic_avtar.png'),
  ic_back: require('../assets/images/ic_back.png'),
  ic_check_radio: require('../assets/images/ic_check_radio.png'),
  ic_close: require('../assets/images/ic_close.png'),
  ic_download: require('../assets/images/ic_download.png'),
  ic_email: require('../assets/images/ic_email.png'),
  ic_filter: require('../assets/images/ic_filter.png'),
  ic_forgot_img: require('../assets/images/ic_forgot_img.png'),
  ic_help: require('../assets/images/ic_help.png'),
  ic_hidden_pass: require('../assets/images/ic_hidden_pass.png'),
  ic_home: require('../assets/images/IC_Home.png'),
  ic_logout1: require('../assets/images/ic_logout_new.png'),
  ic_msg: require('../assets/images/ic_msg.png'),
  ic_otp_img: require('../assets/images/ic_otp_img.png'),
  ic_pass_show: require('../assets/images/ic_pass_show.png'),
  ic_pass: require('../assets/images/ic_pass.png'),
  ic_privacy_policy: require('../assets/images/ic_privacy_policy.png'),
  ic_right_arrow_new: require('../assets/images/ic_right_arrow_new.png'),
  ic_right_round: require('../assets/images/ic_right_round.png'),
  ic_search: require('../assets/images/ic_search.png'),
  ic_transaction_history: require('../assets/images/ic_transaction_history.png'),
  ic_uncheck_radio: require('../assets/images/ic_uncheck_radio.png'),
  ic_user: require('../assets/images/ic_user.png'),
  ic_user1: require('../assets/images/ic_user1.png'),
  InwardRegister: require('../assets/images/InwardRegister.png'),
  logoIcon: require('../assets/images/logoIcon.png'),
  logoLight: require('../assets/images/logoLight.png'),
  MIS: require('../assets/images/MIS.png'),
  ms: require('../assets/images/ms.png'),
  NABL: require('../assets/images/NABL.png'),
  Normal: require('../assets/images/Normal.png'),
  OnBoarding_2: require('../assets/images/OnBoard_3.jpg'),
  OnBoarding_1: require('../assets/images/OnBoarding_5.jpg'),
  Page: require('../assets/images/page.png'),
  PendingTesting: require('../assets/images/PendingTesting.png'),
  PLLOGO: require('../assets/images/PL-logo.png'),
  ic_Print: require('../assets/images/Print.png'),
  ic_PrintLabel: require('../assets/images/PrintLabel.png'),
  ProcessStatus: require('../assets/images/ProcessStatus.png'),
  Profilee: require('../assets/images/Profilee.png'),
  reload: require('../assets/images/reload.png'),
  ic_ScanCopy: require('../assets/images/ScanCopy.png'),
  scheduleIcon: require('../assets/images/scheduleIcon.png'),
  TAP: require('../assets/images/TAP.png'),
  TTR: require('../assets/images/TTR.png'),
  UserBottom: require('../assets/images/UserBottom.png'),
}
